version: '3.8'

services:
  db:
    image: challenge3-db  
    build: ./db  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node-service:
    build: ./api
    image: challenge3-node-service  # 
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    image: challenge3-nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service
volumes:
  db_data:
